spring:
  application:
    name: ci-cd-github-actions
  info:
    build:
      creator: Metehan Gultekin
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8088

#Db connection =http://localhost:8088/h2-console/